version: "3.8"

services:
  postgres:
    container_name: nest-clean-postgres
    image: postgres:12.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-clean
    volumes:
      - ./data/postgres:/data/postgres
