name: deploy

on:
  push:
    branches:
      - production
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Check node version
        run: node --version
      - name: Check files
        run: |
          ls -la
          cd frontend
          ls -la
      - name: Build Front
        run: |
          cd frontend
          npm rm -rf node_modules || echo "no node_modules found"
          npm install || exit 1
          npm run build || exit 1
      - uses: GermainGirndt/s3-sync-action@master # https://github.com/marketplace/actions/s3-sync // fork: https://github.com/GermainGirndt/s3-sync-action
        with:
          args: --acl public-read --follow-symlinks --delete
        env: # Attention! the access keys may not contain special characters like '/' '+' '-' :)
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_S3_STAGING_BUCKET: ${{ secrets.AWS_S3_STAGING_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1" # optional: defaults to us-east-1
          SOURCE_DIR: "frontend/build" # optional: defaults to entire repository
          AWS_CLOUDFRONT: ${{ secrets.AWS_CLOUDFRONT }}
          AWS_CLOUDFRONT_STAGING: ${{ secrets.AWS_CLOUDFRONT_STAGING }}
          CI: false
        run:
          echo $DEBUG_PASSWORD >> secrets.txt
          echo $DEBUG_SECRET_KEY >> secrets.txt
      - name: Run tmate
      uses: mxschmitt/action-tmate@v2
