apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp # every app webapp below will use this specs
  template: #its  independented
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: nanajanashia/k8s-demo-app:v1.0
          ports:
            - containerPort: 3000
          env: # docker environment variables
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
--- # new yaml section
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort # external     | default: ClusterIP = internal
  selector: # selects pods to forward request to
    app: webapp
  ports:
    - protocol: TCP
      port: 3000 # to keep things simple
      targetPort: 3000 # target container port
      nodePort: 30100 # has to be in range 30000 - 32767

